name: CI

on:
  push:
    branches:
      - development
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  CI:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [16]

    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Check types
        run: npx tsc --noEmit
      - name: Test
        run: npm run test
        env:
          SERVER_HOST: 'localhost'
          SERVER_PORT: 3000
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET }}
      - name: Build
        run: npm run build
